// <auto-generated />
using System;
using EduDriveInformationSystem.Domain.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EduDriveInformationSystem.Domain.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250318101727_initialMigrate")]
    partial class initialMigrate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EduDriveInformationSystem.Domain.Models.Entities.UserModel", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserContactNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserFirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserLastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserRole")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = new Guid("459465e1-2d54-4161-a0c1-ed15481264ed"),
                            UserContactNumber = "+27 123 456 789",
                            UserEmail = "admin@drivingschool.com",
                            UserFirstName = "John",
                            UserLastName = "Doe",
                            UserPassword = "hashedPasswordHere",
                            UserRole = 0
                        },
                        new
                        {
                            UserId = new Guid("3c718c17-c474-46b1-afc5-ca03efe38c65"),
                            UserContactNumber = "+27 987 654 321",
                            UserEmail = "instructor@drivingschool.com",
                            UserFirstName = "Jane",
                            UserLastName = "Smith",
                            UserPassword = "hashedPasswordHere",
                            UserRole = 2
                        },
                        new
                        {
                            UserId = new Guid("c879cdfc-dbfe-451d-bb48-1b500cc99ff8"),
                            UserContactNumber = "+27 555 123 456",
                            UserEmail = "sales@drivingschool.com",
                            UserFirstName = "Sarah",
                            UserLastName = "Johnson",
                            UserPassword = "hashedPasswordHere",
                            UserRole = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
